[tool.poetry]
name = "autopentest"
version = "0.1.0"
description = "Multi agent setup using function calling and RAGs to automate penetration testing."
authors = [
    "Julius Henke <mail@juliushenke.com>",
]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.2"
openai = "<2"
tavily-python = "^0.1.9"
langchain-community = "^0.2.0"
uvicorn = "^0.23.2"
pydantic = "<2"
langchain-openai = "^0.1.8"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[build-system]
requires = [
    "poetry-core"
]
build-backend = "poetry.core.masonry.api"
