[tool.poetry]
name = "autopentest"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
openai-functions-agent = {path = "packages/openai-functions-agent", develop = true}
langchain-openai = "^0.1.8"
python-dotenv = "^1.0.1"
googlesearch-python = "^1.2.4"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
rag-conversation = {path = "packages/rag-conversation", develop = true}


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
