[tool.poetry]
name = "autopentest"
version = "0.1.0"
description = "Automate penetration testing using multiple LLM agents with function calling and RAGs"
authors = [
    "Julius Henke <mail@juliushenke.com>",
]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.13"
langchain = "^0.2"
openai = "<2"
tavily-python = "^0.1.9"
langchain-community = "^0.2.0"
uvicorn = "^0.23.2"
pydantic = "<2"
langchain-openai = "^0.1.8"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
nmapthon2 = "^0.1.5"
pinecone = "^4.0.0"
langchain-pinecone = "^0.1.1"
langgraph = "^0.0.69"
nvdlib = "^0.7.7"
langchain-experimental = "^0.0.61"
pinecone-client = "3.2.2"
playwright = "^1.44.0"
lxml = "^5.2.2"
pexpect = "^4.9.0"

langchainhub = "^0.1.20"
[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[build-system]
requires = [
    "poetry-core"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
autopentest = "src.main:main"